lang: "en_US"
metrics: true

discord:
  webhook: ""
  avatarUrl: "https://icons.iconarchive.com/icons/graphicloads/flat-finance/256/dollar-icon.png"
  username: "Shops"
  title:
    buy: "%player% bought x%amount% %item%"
    sell: "%player% sold x%amount% %item%"
  random-color: true
  color:
    h: 199
    s: 100
    b: 100
  buyfield:
    name: "Buy Price"
    value: "%amount%"
    inline: true
  sellfield:
    name: "Sell Price"
    value: "%amount%"
    inline: true
  buyerfield:
    name: "Buyer"
    value: "%player%"
    inline: false
  itemfield:
    name: "Item"
    value: "%item%"
    inline: false
  quantityfield:
    name: "Quantity"
    value: "%quantity%"
    inline: true
  finalpricefield:
    name: "Final Price"
    value: "%amount%"
    inline: true
  typefield:
    name: "Type"
    value: "%type%"
    inline: true

help:
  player:
    - "&e&b&nShops Help"
    - ""
    - "&f/&bshops"
    - "&f/&bshops open &6<&bcategory&6>"
    - ""
  admin:
    - "&e&b&nShops Help"
    - ""
    - "&d<> &f- Required"
    - ""
    - "&f/&bshops"
    - "&f/&bshops open &6<&bcategory&6>"
    - "&f/&bshops create &d<&bcategory&d>"
    - "&f/&bshops remove &d<&bcategory&d>"
    - "&f/&bshops list"
    - "&f/&bshops additem &d<&bcategory&d> &d<&bsell&d> &d<&bbuy&d>"
    - "&f/&bshops edit &d<&bcategory&d>"
    - "&f/&bshops seticon &d<&bcategory&d>"
    - "&f/&bshops setname &d<&bcategory&d> &d<&bname&d>"
    - "&f/&bshops contents &d<&bcategory&d>"
    - ""

receipt:
  item: "PAPER"
  name: "&b%player%'s &eReceipt"
  lore:
    - "&bBuyer: &e%player%"
    - "&bItem: &e%item%"
    - "&bType: &e%type%"
    - "&bQuantity: &e%amount%"
    - "&bFinal Price: &e%finalprice%"

anvils:
  setsellprice: "&8Set Sell Price"
  setbuyprice: "&8Set Buy Price"

guis:
  editprice:
    title: "&8Editing Item Prices"
    setsellprice:
      item: "LIME_STAINED_GLASS_PANE"
      name: "&a&lEdit Sell Price"
      lore:
        - "&7Click to edit the sell price"
    setbuyprice:
      item: "RED_STAINED_GLASS_PANE"
      name: "&a&lEdit Buy Price"
      lore:
        - "&7Click to edit the buy price"
  shopcontent:
    title: "%shop_title% &eContents"
    editmsg: "&e(!) Left-Click to Edit Price"
    removemsg: "&e(!) Middle-Click to Remove"
    close-item:
      item: "BARRIER"
      name: "&C&LClose"
      lore:
        - "&7Click to close inventory"
    previous-page:
      item: "ARROW"
      name: "&e&l<<"
      lore:
        - "&7Click to go back a page"
    next-page:
      item: "ARROW"
      name: "&e&l>>"
      lore:
        - "&7Click to go to next page"
  allshops:
    title: "&8Select a Shop"
    close-item:
      item: "BARRIER"
      name: "&C&LClose"
      lore:
        - "&7Click to close inventory"
    previous-page:
      item: "ARROW"
      name: "&e&l<<"
      lore:
        - "&7Click to go back a page"
    next-page:
      item: "ARROW"
      name: "&e&l>>"
      lore:
        - "&7Click to go to next page"
    shop-icon:
      name: "%shop_title%" # you can also use %shop_name% but it will use the name that was used when creating it. Title is styled
      lore:
        - "&7Click to access shop"
  purchase-inventory:
    title: "&8Purchase / Sell"
    border-item: "LIGHT_BLUE_STAINED_GLASS_PANE"
    increment:
      item: "LIME_STAINED_GLASS_PANE"
      name: "&a&l+ %amount%"
      lore:
        - "&7Click to increment total"
    decrement:
      item: "RED_STAINED_GLASS_PANE"
      name: "&c&l- %amount%"
      lore:
        - "&7Click to decrement total"
    selltotal:
      item: "ORANGE_STAINED_GLASS_PANE"
      name: "&a&lSell %amount%"
      lore:
        - "&7Click to sell total"
    sellall:
      item: "YELLOW_STAINED_GLASS_PANE"
      name: "&a&lSell All"
      lore:
        - "&7Click to sell all"
    iteminfo:
      item: "SUNFLOWER"
      name: "&b&lTotal&f: &e%amount%"
      lore:
        - "&eBuy Total&f: &a$%buy_total%"
        - "&eSell Total&f: &a$%sell_total%"
        - ""
        - "&e(Left-Click) to Purchase"
    iteminfobuyonly:
      item: "SUNFLOWER"
      name: "&b&lTotal&f: &e%amount%"
      lore:
        - "&eBuy Total&f: &a$%buy_total%"
        - ""
        - "&e(Left-Click) to Purchase"
    back-item:
      item: "ARROW"
      name: "&e&l<< Go Back"
      lore:
        - "&7Click to go back to shop contents"
    close-item:
      item: "BARRIER"
      name: "&c&lClose"
      lore:
        - "&7Click to close inventory"
  edit-shop:
    title: "&8Editing Shop: &e%shopname%"
    border-item: "LIGHT_BLUE_STAINED_GLASS_PANE"
    setname:
      item: "PAPER"
      name: "&b%shopname%"
      lore:
        - "&7Click to change the shop name"
    edititems:
      item: "CHEST"
      name: "&bEdit Items"
      lore:
        - "&7Click to edit shop inventory"
        - "&7(Remove / Sell & Buy Price)"
    deleteshop:
      item: "RED_STAINED_GLASS_PANE"
      name: "&cDelete Shop"
      lore:
        - "&7Click to delete the shop"
        - "&c&l(!) &cCannot be undone"
    shop-enabled:
      item: "LIME_WOOL"
      name: "&B%shopname% &eEnabled"
      lore:
        - "&7Click to &cDisable &7this shop"
    shop-disable:
      item: "RED_WOOL"
      name: "&b%shopname% &cDisabled"
      lore:
        - "&7Click to &aEnable &7this shop"
    buyonlyon:
      item: "LIME_WOOL"
      name: "&B%shopname% &eis Buy Only"
      lore:
        - "&7Click to &cDisable &7buy only"
    buyonlyoff:
      item: "RED_WOOL"
      name: "&b%shopname% &cisn't Buy Only"
      lore:
        - "&7Click to &aEnable &7buy only"
    close-item:
      item: "BARRIER"
      name: "&c&lClose"
      lore:
        - "&7Click to close inventory"
  shop:
    previous-page:
      item: "ARROW"
      name: "&e&l<<"
      lore:
        - "&7Click to go back a page"
    next-page:
      item: "ARROW"
      name: "&e&l>>"
      lore:
        - "&7Click to go to next page"
    close-item:
      item: "BARRIER"
      name: "&c&lClose"
      lore:
        - "&7Click to close inventory"
    purchase-item:
      #the custom name will only activate if the item doesn't already have a custom name.
      name: "&e%material_name%"
      lore:
        - ""
        - "&eSell (x1)&f: &a$%sell_price%"
        - "&eBuy (x1)&f: &a$%buy_price%"
    purchase-item-buy-only:
      #the custom name will only activate if the item doesn't already have a custom name.
      name: "&e%material_name%"
      lore:
        - ""
        - "&eBuy (x1)&f: &a$%buy_price%"
  edit-list:
    title: "&8Select a shop to edit"
    border-item: "LIGHT_BLUE_STAINED_GLASS_PANE"
    close-item:
      item: "BARRIER"
      name: "&C&LClose"
      lore:
        - "&7Click to close inventory"
    previous-page:
      item: "ARROW"
      name: "&e&l<<"
      lore:
        - "&7Click to go back a page"
    next-page:
      item: "ARROW"
      name: "&e&l>>"
      lore:
        - "&7Click to go to next page"
    shop-item:
      item: "LIME_STAINED_GLASS_PANE"
      name: "&b%shopname%"
      lore:
        - "&7Click to edit this shop"