lang: "en_US"

discord:
  webhook: ""
  avatarUrl: ""
  username: ""

guis:
  allshops:
    title: "&8Select a Shop"
    close-item:
      item: "BARRIER"
      name: "&C&LClose"
      lore:
        - "&7Click to close inventory"
    previous-page:
      item: "ARROW"
      name: "&e&l<<"
      lore:
        - "&7Click to go back a page"
    next-page:
      item: "ARROW"
      name: "&e&l>>"
      lore:
        - "&7Click to go to next page"
    shop-icon:
      name: "%shop_title%" # you can also use %shop_name% but it will use the name that was used when creating it. Title is styled
      lore:
        - "&7Click to access shop"
  purchase-inventory:
    title: "&8Purchase / Sell"
    border-item: "LIGHT_BLUE_STAINED_GLASS_PANE"
    increment:
      item: "LIME_STAINED_GLASS_PANE"
      name: "&a&l+ %amount%"
      lore:
        - "&7Click to increment total"
    decrement:
      item: "RED_STAINED_GLASS_PANE"
      name: "&c&l- %amount%"
      lore:
        - "&7Click to decrement total"
    selltotal:
      item: "ORANGE_STAINED_GLASS_PANE"
      name: "&a&lSell %amount%"
      lore:
        - "&7Click to sell total"
    sellall:
      item: "YELLOW_STAINED_GLASS_PANE"
      name: "&a&lSell All"
      lore:
        - "&7Click to sell all"
    iteminfo:
      item: "SUNFLOWER"
      name: "&b&lTotal&f: &e%amount%"
      lore:
        - "&eBuy Total&f: &a$%buy_total%"
        - "&eSell Total&f: &a$%sell_total%"
        - ""
        - "&e(Left-Click) to Purchase"
    close-item:
      item: "BARRIER"
      name: "&c&lClose"
      lore:
        - "&7Click to close inventory"
  edit-shop:
    title: "&8Editing Shop: &e%shopname%"
    border-item: "LIGHT_BLUE_STAINED_GLASS_PANE"
    setname:
      item: "PAPER"
      name: "&b%shopname%"
      lore:
        - "&7Click to change the shop name"
    edititems:
      item: "CHEST"
      name: "&bEdit Items"
      lore:
        - "&7Click to edit shop inventory"
        - "&7(Remove / Sell & Buy Price)"
    deleteshop:
      item: "RED_STAINED_GLASS_PANE"
      name: "&cDelete Shop"
      lore:
        - "&7Click to delete the shop"
        - "&c&l(!) &cCannot be undone"
    shop-enabled:
      item: "LIME_WOOL"
      name: "&B%shopname% &eEnabled"
      lore:
        - "&7Click to &cDisable &7this shop"
    shop-disable:
      item: "RED_WOOL"
      name: "&b%shopname% &cDisabled"
      lore:
        - "&7Click to &aEnable &7this shop"
    close-item:
      item: "BARRIER"
      name: "&c&lClose"
      lore:
        - "&7Click to close inventory"
  shop:
    close-item:
      item: "BARRIER"
      name: "&c&lClose"
      lore:
        - "&7Click to close inventory"
    purchase-item:
      #the custom name will only activate if the item doesn't already have a custom name.
      name: "&e%material_name%"
      lore:
        - ""
        - "&eSell (x1)&f: &a$%sell_price%"
        - "&eBuy (x1)&f: &a$%buy_price%"
  edit-list:
    title: "&8Select a shop to edit"
    border-item: "LIGHT_BLUE_STAINED_GLASS_PANE"
    close-item:
      item: "BARRIER"
      name: "&C&LClose"
      lore:
        - "&7Click to close inventory"
    previous-page:
      item: "ARROW"
      name: "&e&l<<"
      lore:
        - "&7Click to go back a page"
    next-page:
      item: "ARROW"
      name: "&e&l>>"
      lore:
        - "&7Click to go to next page"
    shop-item:
      item: "LIME_STAINED_GLASS_PANE"
      name: "&b%shopname%"
      lore:
        - "&7Click to edit this shop"